server:
  port: 9001

spring:
  application:
    name: feather-xd-user-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 #Nacos配置中心地址
        file-extension: yaml #文件拓展格式
        namespace: 14662171-d30c-4727-9869-6c89e9fdc914


#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xd_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
  #邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    port: 465
    username: Brian608@163.com #发送邮件的邮箱地址
    password: xxx #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: Brian608@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxxx
    access-key-secret: xxx
    bucketname: feather-xd
#seata配置
seata:
  tx-service-group: ${spring.application.name}-group
  service:
    grouplist:
      xdclass: 127.0.0.1:8091

    vgroup-mapping:
      feather-xd-user-service-group: feather-xd

